### ISSUE TITLE
error when using go get  github.com/gobuffalo/buffalo/buffalo

### ISSUE THREAD

**Issue by giulianozor** [gobuffalo/genny#35]
Hello,
this worked fine yesterday 23/12/2019 with (probably) version 0.4.1 )v.5.x is 9 hours old right now)

I have a Dockerfile that from golang:1.13.4 uses
go get -u github.com/gobuffalo/buffalo/buffalo

The command fails with the error 

build github.com/gobuffalo/buffalo/buffalo: cannot load github.com/gobuffalo/genny/gogen/gomods: module github.com/gobuffalo/genny@latest found (v0.5.2), but does not contain package github.com/gobuffalo/genny/gogen/gomods

In go.mod I have no reference to genny,so I suppose it is a dependency of buffalo

To be ablle to install buffalo can I use something lie 
git config --global --add url."github.com/gobuffalo/genny@v0.4.1".insteadOf "https://github.com/gobuffalo/genny@latest"
>

Thanks

**Comment by markbates** [comment]
Dupe of #34
