### ISSUE TITLE
Attrs Parse and field uniqueness

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/genny#4]
When calling 

https://github.com/gobuffalo/genny/blob/9033ae798a5a8575a9a9f95bd3f0a2c16f8fa3c1/movinglater/attrs/parse.go#L33

It allows to have duplicated attributes, when using this to generate code usually the plugin will need to validate this.

I wonder if we should keep the first of the same name we receive there.

**Comment by markbates** [comment]
Perhaps return a “duplicate attr name” error?

Thanks.

-----------
Mark Bates

**Comment by paganotoni** [comment]
Thats great, i'll go for it.

**Comment by paganotoni** [comment]
@markbates sent #6
