### ISSUE TITLE
Add other common types for attr

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/genny#5]
We may need to add other common types mapping in here:

https://github.com/gobuffalo/genny/blob/9033ae798a5a8575a9a9f95bd3f0a2c16f8fa3c1/movinglater/attrs/attrs.go#L16

In order to be able to support Pop

**Comment by markbates** [comment]
Yes! That method is incomplete. Not even close to ready. :)

Thanks.

-----------
Mark Bates

**Comment by paganotoni** [comment]
@markbates added types in #8
