### ISSUE TITLE
Hey @fasmat,

### ISSUE THREAD

**Issue by LolyPopToyou** [gobuffalo/genny#54]
Hey @fasmat,

I just figured out that current runners doesn't support `fs.FS`, so this issue would be a great enhancement.

What I have in mind is a single `NewRunner(fs.FS)` : 
- if you want a dry runner use `NewRunner(fstest.MapFS{})`
- if you want a wet runner use `NewRunner(os.DirFS("."))`

That said `DryRunner` and `WetRunner` could be kept, but they will just call `NewRunner` with the appropriate `fs`.

What do you think ?

EDIT: seems like I went a little too fast, `fs.FS` is only a readable interface, so it cannot be used by a runner. Maybe this will change [in the future](https://www.github.com/golang/go/issues/45757).

_Originally posted by @tbruyelle in https://github.com/gobuffalo/genny/issues/43#issuecomment-1372213050_

**Comment by sio4** [comment]
seems like mistakenly created.
